/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DON
 */
public class SimpleCalculator extends javax.swing.JFrame {

    double num,ans;
    int calculation;
    public SimpleCalculator() {   
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("img.jpeg")).getImage());
    }
    
    public void arithemetic_operation(){
        try{
            switch(calculation)
        {       
            case 1: 
                ans = num + Double.parseDouble(txtField.getText());
                txtField.setText(Double.toString(ans));
                break;
            case 2: 
                ans = num - Double.parseDouble(txtField.getText());
                txtField.setText(Double.toString(ans));
                break;
            case 3: 
                ans = num * Double.parseDouble(txtField.getText());
                txtField.setText(Double.toString(ans));
                break;
            case 4: 
                ans = num / Double.parseDouble(txtField.getText());
                txtField.setText(Double.toString(ans));
                break;
        }
        } catch(Exception e) {
            System.out.println("This program will give an error.");
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        timesButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        txtField = new javax.swing.JTextField();
        cButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(450, 200));
        setResizable(false);

        oneButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        timesButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timesButton.setText("x");
        timesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesButtonActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divButton.setText("÷");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        delButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delButton.setText("del");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        equalsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        equalsButton.setText("=");
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        txtField.setEditable(false);
        txtField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldKeyPressed(evt);
            }
        });

        cButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        pointButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pointButton.setText(".");
        pointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sevenButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fiveButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sixButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(minusButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(eightButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(nineButton))
                                            .addComponent(cButton))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(timesButton)
                                            .addComponent(delButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oneButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(twoButton))
                                    .addComponent(fourButton))
                                .addGap(18, 18, 18)
                                .addComponent(threeButton)
                                .addGap(18, 18, 18)
                                .addComponent(addButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zeroButton)
                                .addGap(18, 18, 18)
                                .addComponent(pointButton)
                                .addGap(18, 18, 18)
                                .addComponent(divButton)
                                .addGap(18, 18, 18)
                                .addComponent(equalsButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, cButton, delButton, divButton, eightButton, equalsButton, fiveButton, fourButton, minusButton, nineButton, oneButton, pointButton, sevenButton, sixButton, threeButton, timesButton, twoButton, zeroButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton)
                    .addComponent(delButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nineButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sevenButton)
                        .addComponent(eightButton)
                        .addComponent(timesButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixButton)
                    .addComponent(fiveButton)
                    .addComponent(fourButton)
                    .addComponent(minusButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton)
                    .addComponent(twoButton)
                    .addComponent(threeButton)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equalsButton)
                    .addComponent(pointButton)
                    .addComponent(zeroButton)
                    .addComponent(divButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addButton, cButton, delButton, divButton, eightButton, equalsButton, fiveButton, fourButton, minusButton, nineButton, oneButton, pointButton, sevenButton, sixButton, threeButton, timesButton, twoButton, zeroButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "5");
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "1");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "2");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        try{
           
        } catch(Exception e){
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "3");
        }      
        
    }//GEN-LAST:event_threeButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "4");
        } catch(Exception e){
            
        }      
        
    }//GEN-LAST:event_fourButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "6");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_sixButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
         try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "7");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
         try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "8");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
         try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "9");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_nineButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
         try{
            this.txtField.requestFocus();
            txtField.setText(txtField.getText() + "10");
        } catch(Exception e){
            
        }      
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        this.txtField.requestFocus();
        //txtField.setText(txtField.getText() + "+");
        try {
            num = Double.parseDouble(txtField.getText());
            calculation = 1;
            txtField.setText("");
            jLabel1.setText(num + " + ");
        } catch (Exception e) {
            
        } 
    }//GEN-LAST:event_addButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        this.txtField.requestFocus();
        //txtField.setText(txtField.getText() + "-");
        try {
            num = Double.parseDouble(txtField.getText());
            calculation = 2;
            txtField.setText("");
            jLabel1.setText(num + " - ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void timesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesButtonActionPerformed
        this.txtField.requestFocus();
        //txtField.setText(txtField.getText() + "X");
        try {
            num = Double.parseDouble(txtField.getText());
            calculation = 3;
            txtField.setText("");
            jLabel1.setText(num + " x ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_timesButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        this.txtField.requestFocus();
        //txtField.setText(txtField.getText() + "÷");
        try {
            num = Double.parseDouble(txtField.getText());
            calculation = 4;
            txtField.setText("");
            jLabel1.setText(num + " ÷ ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_divButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        this.txtField.requestFocus();
        int length = txtField.getText().length();
        int number = length - 1;
        String store;
        if (length > 0){
            StringBuilder back = new StringBuilder(txtField.getText());
            back.deleteCharAt(number);
            store = back.toString();
            txtField.setText(store);
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        this.txtField.requestFocus();
        try {
            arithemetic_operation();
            jLabel1.setText("");
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void pointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointButtonActionPerformed
        this.txtField.requestFocus();
        try {
            if (txtField.getText().equals("")){
                txtField.setText(txtField.getText() + "0.");
                //txtField.setText(txtField.getText() + ".");
            }
            else{
                txtField.setText(txtField.getText() + ".");
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_pointButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        try{
            this.txtField.requestFocus();
            txtField.setText("");
            jLabel1.setText("");
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_cButtonActionPerformed

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldActionPerformed

    private void txtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeyPressed
        if (evt.getExtendedKeyCode() == 27) {
            cButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 8) {
            delButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 48 || evt.getExtendedKeyCode() == 96) {
            zeroButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 49 || evt.getExtendedKeyCode() == 97) {
            oneButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 50 || evt.getExtendedKeyCode() == 98) {
            twoButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 51 || evt.getExtendedKeyCode() == 99) {
            threeButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 52 || evt.getExtendedKeyCode() == 100) {
            fourButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 53 || evt.getExtendedKeyCode() == 101) {
            fiveButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 54 || evt.getExtendedKeyCode() == 102) {
            sixButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 55 || evt.getExtendedKeyCode() == 103) {
            sevenButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 56 || evt.getExtendedKeyCode() == 104) {
            eightButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 57 || evt.getExtendedKeyCode() == 105) {
            nineButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 61 || evt.getExtendedKeyCode() == 107) {
            addButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 45 || evt.getExtendedKeyCode() == 109) {
            minusButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 106) {
            timesButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 111) {
            divButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 46 || evt.getExtendedKeyCode() == 110) {
            pointButtonActionPerformed(null);
        }
        if (evt.getExtendedKeyCode() == 10 ) {
            equalsButtonActionPerformed(null);
        }
        //System.out.println(evt.getExtendedKeyCode());
    }//GEN-LAST:event_txtFieldKeyPressed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton timesButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JTextField txtField;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
